// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnapViewer.Data;

#nullable disable

namespace SnapViewer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SnapViewer.Models.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "width");

                    b.Property<decimal>("X")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "x");

                    b.Property<decimal>("Y")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "y");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("SnapViewer.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("SnapViewer.Models.Annotation", b =>
                {
                    b.HasOne("SnapViewer.Models.Image", "Image")
                        .WithMany("Annotations")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("SnapViewer.Models.Image", b =>
                {
                    b.Navigation("Annotations");
                });
#pragma warning restore 612, 618
        }
    }
}
